#!/usr/bin/env bash
# shellcheck disable=SC1091
source "$HOME/dev/binx/profile/sane_fn.sh"

############### VENV ###############
# Emulate the pipenvs's activate, because we can't source things in direnv
layout_pipenv
#layout_poetry
#dotenv

############### Exports ###############
PROJ_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export PROJ_DIR
Green "-M- exporting PROJ_DIR: $PROJ_DIR"

if which tmux > /dev/null 2>&1; then
    tmux rename-window "$(basename "$PROJ_DIR")"
fi

export senv="source $PROJ_DIR/scripts/env.sh"
export PYTHONPATH=$PROJ_DIR
#export TW_FZF_ROOT="$HOME/dev"
export PIPENV_VENV_IN_PROJECT=1  # creates .venv
#export POETRY_VIRTUALENVS_IN_PROJECT=1  # creates .venv

PATH_add $PROJ_DIR/scripts

export RUN_ENV=local

######################################## DB ########################################
#export DB_HOST=localhost
#export DB_PORT=54320
#export DB_NAME=powerpool-prod
#export DB_USER=powerpool_prod
#export DB_PASSWORD=...
#export DB_SSL=true
#export DB_SSL_MODE=require  # default: prefer, allow, disable
#export DB_URL="postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSL_MODE"
# export SIM_SQLALCHEMY_DATABASE_URI="postgresql://powerpool_simulation:...@central-1-rds-1.civphdrjeexi.eu-central-1.rds.amazonaws.com:5432/powerpool_simulation?sslmode=require"

######################################## github ########################################
export GH_HOST=github.com
######################################## Credentials ########################################
source ~/dev/crypt/dot_direnv_creds

### unset for PyPi
unset TWINE_USERNAME
unset TWINE_PASSWORD
