# https://tox.wiki/en/latest/config.html

[tox]
minversion = 3.25.0
isolated_build = True
envlist = py38,py39,py310

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310

[testenv]
usedevelop = true
deps =
    pytest
    pytest-cov
    pytest-mock
    #pytest-asyncio
    black
    coverage
    #requests
allowlist_externals =
    make
    /usr/bin/bash
commands =
    black src/raw_sql
    make coverage
